=== knovash/hospitaljaxb/src/main/resources/schema.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="hospital">

    <element name="root">
        <complexType>
            <sequence>

                <element name="hospital">
                    <complexType>
                        <sequence>
                            <element name="address" type="string"/>

                            <element name="DEPARTMENTS">
                                <complexType>
                                    <sequence>

                                        <element name="department">
                                            <complexType>
                                                <sequence>
                                                    <element name="name" type="string"/>
                                                    <element name="DOCTORS">
                                                        <complexType>
                                                            <sequence>

                                                                <element name="doctor">
                                                                    <complexType>
                                                                        <sequence>

                                                                            <element name="name" type="string"/>
                                                                            <element name="age" type="string"/>
                                                                            <element name="weight" type="string"/>
                                                                            <element name="spec" type="string"/>


                                                                        </sequence>
                                                                    </complexType>
                                                                </element>


                                                            </sequence>
                                                        </complexType>
                                                    </element>


                                                </sequence>
                                            </complexType>
                                        </element>


                                    </sequence>
                                </complexType>
                            </element>

                            <element name="PATIENTS">
                                <complexType>
                                    <sequence>

                                        <element name="patient">
                                            <complexType>
                                                <sequence>

                                                    <element name="name" type="string"/>
                                                    <element name="age" type="string"/>
                                                    <element name="weight" type="string"/>
                                                    <element name="spec" type="string"/>


                                                </sequence>
                                            </complexType>
                                        </element>


                                    </sequence>
                                </complexType>
                            </element>


                        </sequence>
                    </complexType>
                </element>

            </sequence>
        </complexType>
    </element>
</schema>

=== knovash/hospitaljaxb/target/classes/jaxb.xml
<?xml version="1.0" encoding="UTF-8"?>
<root xmlns="hospital"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="hospital schema.xsd">
<hospital>
    <address>Minsk</address>
    <DEPARTMENTS>
        <department>
            <DOCTORS>
                <doctor>
                    <name>Denis</name>
                    <age>44</age>
                    <weight>88</weight>
                    <spec>dentist</spec>
                </doctor>
                <doctor>
                    <name>Denis</name>
                    <age>44</age>
                    <weight>88</weight>
                    <spec>dentist</spec>
                </doctor>
            </DOCTORS>
            <name>DENTAL</name>
        </department>
        <department>
            <DOCTORS>
                <doctor>
                    <name>Sergey</name>
                    <age>66</age>
                    <weight>77</weight>
                    <spec>surgeon</spec>
                </doctor>
                <doctor>
                    <name>Sergey</name>
                    <age>66</age>
                    <weight>77</weight>
                    <spec>surgeon</spec>
                </doctor>
            </DOCTORS>
            <name>SURGERY</name>
        </department>
    </DEPARTMENTS>
    <PATIENTS>
        <patient>
            <name>Alex</name>
            <age>33</age>
            <weight>66</weight>
        </patient>
        <patient>
            <name>Alex</name>
            <age>33</age>
            <weight>66</weight>
        </patient>
    </PATIENTS>
</hospital>
</root>
